# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JitsiLibTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JitsiLibTest

  target 'JitsiLibTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'JitsiLibTest-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JitsiLibTest-tvOS

  target 'JitsiLibTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
